name: CI/CD Pipeline VPS Kuldi

on:
  push:
    branches:
      - staging
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Bagian deploy ke VPS
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            # Jika yang di-push adalah branch MAIN (Production)
            if [ "${{ github.ref }}" = "refs/heads/main" ]; then
              echo "Deploying to Production Environment..."
              cd /path/ke/folder/production # Nanti diganti Azhar
              git pull origin main
              npm install
              npx prisma generate
              npx prisma db push --accept-data-loss
              npm run build
              # pm2 restart api-prod
              
            # Jika yang di-push adalah branch STAGING
            elif [ "${{ github.ref }}" = "refs/heads/staging" ]; then
              echo "Deploying to Staging Environment..."
              cd /path/ke/folder/staging # Nanti diganti Azhar
              git pull origin staging
              npm install
              npx prisma generate
              npx prisma db push --accept-data-loss
              npm run build
              # pm2 restart api-staging
            fi